### ISSUE TITLE
Popper with auctex

### ISSUE THREAD

**Issue by haji-ali** [karthink/popper#11]
I just installed this package and I am excited about trying it in my daily setup.

But I have a use-case that is conflicting with popper and I am wondering what's the correct way to deal with it.
After compiling a latex document, a list of errors and warnings are shown (if any). I decided to designates this as a popup with popper. But then if I click on an error AUCTeX tries to split the window to show details of the error. This fails with a message `Cannot split side window or parent of side window`. What is the correct setup for such a case?

Ideally, I would like the popup window to split into another two popup window (one for the list of errors and one for the error details). Then if I close any of the two popup windows all popups are closed as usual.

**Comment by karthink** [comment]
Try this (after loading popper) and let me know if it works.

```elisp
(defun popper-select-popup-at-bottom (buffer &optional _alist)
  "Display and switch to popup-buffer BUFFER at the bottom of the screen."
  (let ((window (display-buffer-at-bottom
                 buffer
                 '((window-height . (lambda (win)
                                      (fit-window-to-buffer
                                       win
                                       (floor (frame-height) 3)
                                       (floor (frame-height) 6))))))))
    (select-window window)))
```

If it does then you can rename it to something else, like `my-popper-select-popup-at-bottom`, and then add

```elisp
(setq popper-display-function #'my-popper-select-popup-at-bottom)
```

to your popper config where you define your reference buffers.

> Then if I close any of the two popup windows all popups are closed as usual.

There is no way to close two popups without without closing ALL open popups. You can do this with a double prefix argument to `popper-toggle-latest`, i.e. `C-u C-u M-x popper-toggle-latest` or `C-u C-u` before your key binding for `popper-toggle-latest`.

Alternatively you can bind this function to a key and use it to close all popups.

```elisp
(defun my-popper-bury-all
  (interactive)
  (popper-bury-all))
```

----

Note that this method will cause all popups to be displayed in regular windows instead of side-windows. There are more targeted solutions available if you customize `display-buffer-alist` or use the Shackle package (as I explain in the documentation and youtube video), so that only your AucTeX buffers of interest are displayed in regular windows.
