### ISSUE TITLE
end-of-buffer when switching to pop-up

### ISSUE THREAD

**Issue by plvoit** [karthink/popper#55]
Dear karthink,
I'm trying to figure out how to automatically keep the cursor at the bottom of the pop-up buffer, especially when I switch to it.
Mainly I want to do this because I have my Python-Shell Output in the popup buffer.

I managed to do it, if Python-Shell does not run in a popup buffer like this: (taken from here:
https://stackoverflow.com/questions/8402838/jumping-to-end-of-python-output-buffer-in-emacs)

(defadvice py-postprocess-output-buffer (after my-py-postprocess-output-buffer activate)
  (run-with-idle-timer 0 nil (lambda ()
                               (let ((output-win (get-buffer-window py-output-buffer))
                                     (orig-win (selected-window)))
                                 (when output-win
                                   (select-window output-win)
                                   (end-of-buffer)
                                   (select-window orig-win))))))

I also tried this:
(add-hook 'popper-open-popup-hook 'end-of-buffer) ;;doesnt work

Do you have any advice how this could be achieved?
Thanks a lot for your awesome plug in!
Best, plvoit

**Comment by karthink** [comment]
Hi @plvoit,

The hook method is the preferred way and should work.

I tried

``` emacs-lisp
(add-hook 'popper-open-popup-hook #'end-of-buffer)
```

and it worked as expected in every popup buffer, including the comint Python buffer that `run-python` spawns.  What happens when you try this hook method?  Could you check after running `toggle-debug-on-error`?

-----

Note that the above method works only when you switch to it using Popper.  If you would like the point to move to end-of-buffer no matter how the window is displayed, you can use a display-buffer body function (see `(info "(elisp) Buffer Display Action Alists")`).

**Comment by plvoit** [comment]
Hi @karthink ,
thank you for your reply. Your solution works! The weird behaviour regarding the cursor apparently came from the elpy-package. When I switch it off and just work in the normal python-mode everything works fine.
Thanks again,
plvoit
