### ISSUE TITLE
noselect/unfocus option?

### ISSUE THREAD

**Issue by MicahElliott** [karthink/popper#57]
Wondering if there's a way to pop up popper without it taking focus. Didn't find an option or mention in the readme.

Example use case: using magit, it's nice to [automatically display the process buffer](https://github.com/magit/magit/wiki/Tips-and-Tricks#automatically-displaying-the-process-buffer). And that process buffer is great for popper. But every time you stage a hunk or do almost anything in magit, focus goes to the process buffer (popper), and then you have to keep switching back to `magit-status` window.

I think it's common to want to use popper to just take a quick of view of a buffer without ever touching it. Then use `popper-toggle-latest` (via nice binding) at some later point to close popper, without ever having to visit the actual popper window.

**Comment by MicahElliott** [comment]
Might have figured this out. Here's what seems to be working:
```
(setq popper-display-function #'popper-display-popup-at-bottom)
```

It was originally set to `popper-select-popup-at-bottom`, which seems like a similar equivalent. Happy to hear if this seems like the right approach.

Really appreciate your work on popper; really nice tool.

**Comment by karthink** [comment]
Yeah, that'll do it.  More generally, you might want some popups to steal focus and others to not.

In that case you can set `popper-display-control` to `nil`, so that Popper does not mess with displaying buffers at all, and add rules to your `display-buffer-alist` specifying how you want each kind of "popup" to displayed.  This can include all possibilities: window type, height, position, selection etc.

Other popup managers like `popwin` and Doom Emacs' `+popup` provide a `:select t` option that you can set when defining popup rules.  Popper doesn't do that since it aims to be completely orthogonal to the user's display-buffer configuration.
